### ISSUE TITLE
[Egg_LetterPhoneme] Egg_letters_Tuto is not played

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura_arabic#644]
1. TextMeshPro on component Text isn't RTL
UnityEngine.Debug:LogWarning(Object)
Antura.UI.TextRender:checkConfiguration() (at Assets/_app/_scripts/UI/Text/TextRender.cs:94)
Antura.UI.TextRender:Awake() (at Assets/_app/_scripts/UI/Text/TextRender.cs:62)
UnityEngine.Object:Instantiate(GameObject)
Antura.Minigames.Egg.EggButtonsBox:CreateButton() (at Assets/_games/Egg/_scripts/EggButtonsBox.cs:101)
Antura.Minigames.Egg.EggButtonsBox:AddButton(ILivingLetterData) (at Assets/_games/Egg/_scripts/EggButtonsBox.cs:45)
Antura.Minigames.Egg.EggQuestionState:SetAndShowEggButtons() (at Assets/_games/Egg/_scripts/States/EggQuestionState.cs:74)
Antura.Minigames.Egg.EggQuestionState:<OnEggEnterComplete>m__0() (at Assets/_games/Egg/_scripts/States/EggQuestionState.cs:60)
Antura.Audio.AudioManager:Update() (at Assets/_app/_scripts/Audio/AudioManager.cs:529)

2. Cannot find id 'Egg_letters_Tuto' in table LocalizationTable
UnityEngine.Debug:LogWarning(Object)
Antura.Database.DatabaseObject:GetById(SerializableDataTable`1, String) (at Assets/_app/_scripts/Database/DatabaseObject.cs:143)
Antura.Database.DatabaseManager:GetLocalizationDataById(String) (at Assets/_app/_scripts/Database/DatabaseManager.cs:352)
Antura.Core.LocalizationManager:GetLocalizationData(String) (at Assets/_app/_scripts/_Core/Localization/LocalizationManager.cs:48)
Antura.Audio.AudioManager:PlayDialogue(String) (at Assets/_app/_scripts/Audio/AudioManager.cs:328)
Antura.Minigames.MinigamesAudioManager:PlayDialogue(LocalizationDataId, Action) (at Assets/_app/_scripts/Minigames/Context/MinigamesAudioManager.cs:34)
Antura.Minigames.Egg.EggPlayState:EnterState() (at Assets/_games/Egg/_scripts/States/EggPlayState.cs:100)
Antura.FSM.StateMachineManager:set_CurrentState(IState) (at Assets/_app/_scripts/Minigames/FSM/StateMachineManager.cs:27)
Antura.Minigames.MiniGameController:SetCurrentState(IState) (at Assets/_app/_scripts/Minigames/Controller/MiniGameController.cs:50)
Antura.Minigames.Egg.EggQuestionState:OnQuestionAudioComplete() (at Assets/_games/Egg/_scripts/States/EggQuestionState.cs:132)
Antura.Minigames.Egg.<PlayButtonsAudio>c__AnonStorey2:<>m__0() (at Assets/_games/Egg/_scripts/EggButtonsBox.cs:417)
Antura.Minigames.Egg.<PlayButtonAudio>c__AnonStorey0:<>m__6() (at Assets/_games/Egg/_scripts/EggButton.cs:86)

**Comment by FrancyCavallari** [comment]
The Localization ID has been renamed to "Egg_letterphoneme_Tuto"

**Comment by davidebarbieri** [comment]
Fixed the first warning,

for the second warning,
LocalizationDataId must be exported to reflect this

**Comment by FrancyCavallari** [comment]
ok for the first warning... I keep the issue open for the second one

**Comment by davidebarbieri** [comment]
Cannot find id 'Egg_letters_Tuto' in table LocalizationTable

**Comment by StefanoCecere** [comment]
Egg_letters_Tuto doesn't exists because we are using only Egg_letterphoneme and Egg_buildword

i coulnd't reproduce how to make it call Egg_letters_Tuto!

**Comment by StefanoCecere** [comment]
should be fixed by ecc954c229bb6e1d5f3f745e0fc940b58710ab2a

**Comment by FrancyCavallari** [comment]
I still get 
`Cannot find id 'Egg_letters_Tuto' in table LocalizationTable`

I guess that @davidebarbieri can now call Egg_letterphoneme_Tuto and Egg_buildword_Tuto since Stefano has updated the LocalizationIDs
