### ISSUE TITLE
[Book] Green checkmark in the Vocabulary is not nice/clear

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura_arabic#654]
1. Since it's so small, better to use an icon with less detail it gets "noisy"
2. Its semi-transparent state is not coherent/clear (the selected letter in the scrolling list has a semi-transparent checkmark while the letter on the right panel has a solid marker)
3. In some cases it covers the diacritics (like in the image below)  

![image](https://user-images.githubusercontent.com/17926293/35149212-87711d34-fd15-11e7-8e6e-dcf7d2185beb.png)

I would use a simple check mark like this one
![image](https://user-images.githubusercontent.com/17926293/35149386-2a8d8a3e-fd16-11e7-9ef4-b3ef061ec084.png)

**Comment by StefanoCecere** [comment]
fixed with 096dd79e35ce1a37440c274e9804668dbae9e176

**Comment by FrancyCavallari** [comment]
the point 2 is still present:
2. Its semi-transparent state is not coherent/clear (the selected letter in the scrolling list has a semi-transparent checkmark while the letter on the right panel has a solid marker)
