### ISSUE TITLE
[Arabic] Remove all letters with "shaddah" from the game

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura_arabic#710]
Safaa wrote:
I removed the sign from the words in the VocabularyDB as we don't teach the sign early on in the reading process. We can remove the variation itself from the games.
Is it doable to remove the shaddah variation from the games? We can keep it in the book as we also have signs that are not taught in the games but they can be familiar with in the book (maddah, tanwin etc).
And if it's only in the book, we solve the problem of pronouncing within a word. Then, only display the sign itself in the book, without letters.

**Comment by FrancyCavallari** [comment]
The best pedagogical approach is to expose the kids to “shaddah” in the context of a word… but never play with individual letters with “shaddah”: the focus of the game is the learning to the 4 main diacritic signs "fathah, dammah, kasrah, sukun"!
>>> So we plan to:
Include “shaddah” in all words to have them properly written with the double diacritic when needed (Safaa)
Modify the ArabicHelper to remove “shaddah” everytime a word is split into letters and everytime that a comparison between letters is done (Stefano)
Check that all the Teacher Filters & Builders are working fine after the change in the ArabicHelper (Michele?)
NOTE: No new letter sound will be needed because all letters with “shaddah” (part of a word) will become individual letters without “shaddah”, so they will have either no diacritic (“sukun” sound) or “fathah, dammah, kasrah” (with their specific sounds).

**Comment by StefanoCecere** [comment]
done.
i left the shaddah variation in the book, for now.
the word.split converts all letters+shaddah in just letters

**Comment by FrancyCavallari** [comment]
We should remove/disable all the letters with shaddah from the LetterDB and from the Book... because otherwise they can appear as wrong answers
![image](https://user-images.githubusercontent.com/17926293/36060208-1392789a-0e45-11e8-8aaa-f0c62bfb83cf.png)

We should remove them also from the Book... because cannot play any "correct" sound when we select them.
![image](https://user-images.githubusercontent.com/17926293/36060253-0cb52684-0e46-11e8-9aa9-9402d9040234.png)

**Comment by FrancyCavallari** [comment]
In the latest build it's ok...
... but we still don't have a robust process to reimport the DB without any letter with shaddah
